name: Deploy Alpha

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build:
    name: connect server
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ALPHA_HOST }}
        username: ${{ secrets.ALPHA_USERNAME }}
        password: ${{ secrets.ALPHA_PASSWORD }}
        port: ${{ secrets.ALPHA_PORT }}
        script: |
          cd alpha.dnr.dev
          docker-compose down
          docker-compose pull
          docker-compose up

  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
