name: Deploy[alpha]

on:
  workflow_dispatch:

jobs:
  build:
    name: connect server
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ALPHA_HOST }}
        username: ${{ secrets.ALPHA_USERNAME }}
        password: ${{ secrets.ALPHA_PASSWORD }}
        port: ${{ secrets.ALPHA_PORT }}
        script: |
          cd dnr.dev
          docker-compose -f alpha.yml down --remove-orphans
          git pull
          docker-compose -f alpha.yml pull
          docker-compose -f alpha.yml up -d