name: Deploy Alpha - admin

on:
  workflow_dispatch:

jobs:
  build:
    name: connect server
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ALPHA_HOST }}
        username: ${{ secrets.ALPHA_USERNAME }}
        password: ${{ secrets.ALPHA_PASSWORD }}
        port: ${{ secrets.ALPHA_PORT }}
        script: |
          cd alpha.dnr.dev
          echo y | docker-compose -f alpha.yml rm -sv alpha-admin
          docker-compose -f alpha.yml pull admin
          docker-compose -f alpha.yml up -d admin